# Generated by Django 5.1.3 on 2024-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CholesterolAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chol_total', models.FloatField(blank=True, null=True)),
                ('chol_hdl', models.FloatField(blank=True, null=True)),
                ('chol_ldl', models.FloatField(blank=True, null=True)),
                ('chol_triglycerides', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('result_positive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_blood_cells', models.FloatField(blank=True, null=True)),
                ('white_blood_cells', models.FloatField(blank=True, null=True)),
                ('platelets', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
                ('hematocrit', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabete_glucose', models.FloatField(blank=True, null=True)),
                ('diabete_hba1c', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('result_positive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IstAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_vih', models.CharField(blank=True, max_length=50, null=True)),
                ('ist_syphilis', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('result_positive', models.BooleanField(default=False)),
            ],
        ),
    ]
