# Generated by Django 5.1.3 on 2024-12-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol_analysesdoc', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_analysesdoc', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diabete_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='cholesterol_analyses',
            field=models.ManyToManyField(blank=True, to='analyses.cholesterolanalysis'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='common_analyses',
            field=models.ManyToManyField(blank=True, to='analyses.commonanalysis'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='consultations',
            field=models.ManyToManyField(blank=True, to='users.consultation'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_created', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='diabetes_analyses',
            field=models.ManyToManyField(blank=True, to='analyses.diabetesanalysis'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='rendezvous',
            field=models.ManyToManyField(blank=True, to='users.rdv'),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ist_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ist_analysesdoc', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='ist_analyses',
            field=models.ManyToManyField(blank=True, to='analyses.istanalysis'),
        ),
    ]
