# Generated by Django 4.2.6 on 2024-12-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rdv_status'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cholesterolanalysis',
            name='patientname',
        ),
        migrations.RemoveField(
            model_name='commonanalysis',
            name='patientname',
        ),
        migrations.RemoveField(
            model_name='diabetesanalysis',
            name='patientname',
        ),
        migrations.RemoveField(
            model_name='istanalysis',
            name='patientname',
        ),
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='chol_hdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='chol_ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='chol_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='chol_triglycerides',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cholesterolanalysis',
            name='result_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='hematocrit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='hemoglobin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='platelets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='red_blood_cells',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonanalysis',
            name='white_blood_cells',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesanalysis',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesanalysis',
            name='diabete_glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesanalysis',
            name='diabete_hba1c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesanalysis',
            name='result_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='nom_dossier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AlterField(
            model_name='istanalysis',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='istanalysis',
            name='ist_syphilis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='istanalysis',
            name='ist_vih',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='istanalysis',
            name='result_positive',
            field=models.BooleanField(default=False),
        ),
    ]
