# Generated by Django 5.1.3 on 2024-12-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_initial'),
        ('users', '0004_consultation_created_by_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholesterolanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='commonanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='diabetesanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_analyses', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='istanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ist_analyses', to='users.doctor'),
        ),
    ]
