# Generated by Django 5.1.3 on 2024-12-10 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_cholesterolanalysis_created_by_and_more'),
        ('users', '0004_consultation_created_by_patient_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cholesterol_analyses', models.ManyToManyField(blank=True, to='analyses.cholesterolanalysis')),
                ('common_analyses', models.ManyToManyField(blank=True, to='analyses.commonanalysis')),
                ('consultations', models.ManyToManyField(blank=True, to='users.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_created', to='users.doctor')),
                ('diabetes_analyses', models.ManyToManyField(blank=True, to='analyses.diabetesanalysis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='users.doctor')),
                ('ist_analyses', models.ManyToManyField(blank=True, to='analyses.istanalysis')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('rendezvous', models.ManyToManyField(blank=True, to='users.rdv')),
            ],
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
