# Generated by Django 4.2.6 on 2024-07-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('date', models.DateField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.CreateModel(
            name='IstAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vih', models.BooleanField()),
                ('syphilis', models.BooleanField()),
                ('hepatite', models.BooleanField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.examen')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.medecin'),
        ),
        migrations.AddField(
            model_name='examen',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient'),
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique_consultations', models.JSONField()),
                ('historique_examens', models.JSONField()),
                ('ordonnances', models.JSONField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.medecin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DiabeteAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabete_glucose', models.FloatField()),
                ('diabete_ha1c', models.FloatField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('diagnostique', models.CharField(max_length=255)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CholesterolAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chol_total', models.FloatField()),
                ('chol_hdl', models.FloatField()),
                ('chol_ldl', models.FloatField()),
                ('chol_triglycerides', models.FloatField()),
                ('resultat_positif', models.BooleanField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.examen')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseCourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globule_rouge', models.FloatField()),
                ('globule_blanc', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('platelets', models.FloatField()),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.examen')),
            ],
        ),
    ]
