# Generated by Django 4.2.6 on 2024-11-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='anneeNaissance',
        ),
        migrations.AddField(
            model_name='doctor',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
