# Generated by Django 4.2.6 on 2024-11-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_doctor_anneenaissance_doctor_datenaissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dateNaissance',
            new_name='anneeNaissance',
        ),
    ]
