# Generated by Django 5.1.3 on 2024-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_doctor_adressehopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Docteur'), ('patient', 'Patient')], max_length=10),
        ),
    ]
