# Generated by Django 4.2.6 on 2024-11-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_datenaissance_patient_anneenaissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dateNaissance',
            new_name='anneeNaissance',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='anneeNaissance',
            new_name='dateNaissance',
        ),
    ]
