# Generated by Django 5.1.3 on 2024-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_consultation_created_by_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adresseHopital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
