# Generated by Django 4.2.6 on 2024-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_rendezvous_patient_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('nom', 'prenom')},
        ),
    ]
