# Generated by Django 5.1.3 on 2024-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_demandes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Reporté', 'Reporté')], default='En attente', max_length=20),
        ),
    ]
