# Generated by Django 4.2.6 on 2024-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('attended', 'Le patient est venu'), ('missed', "Le patient n'est pas venu")], default='pending', max_length=10),
        ),
    ]
